### ISSUE TITLE
IncorrectOrUnknownPaymentDetails

### ISSUE THREAD

**Issue by pseudozach** [nbd-wtf/immortan#2]
setup: I'm running cliche.jar on a VM, lntxbot is using it as a backend (probably irrelevant)

- I have an HC with [motherbase](https://1ml.com/node/021e7ea08e31a576b4fd242761d701452a8ac98113eac3074c153db85d2dcc7d27)  and I can create an invoice, pay it with my other node-X.
- When I check my balance on cliche, it's all good, balance is there.
- When I create the same/smaller amount invoice from my node-X and try to pay with cliche, I get this error:
> Payment 4567b1b055e1bd235e7e3217c4d7a94d2f4835150e36cc4b88f0939dd1b6de8c failed.\n\n- IncorrectOrUnknownPaymentDetails at first hop

I opened the issue in this repo because I think it's coming from immortan but I'm also unsure if it's a simple config like a max-fee or max-hop setting or some other problem.

**Comment by fiatjaf** [comment]
`IncorrectOrUnknownPaymentDetails` generally means the invoice has expired on the target node. Could also be that either your cliche or the target node are out of sync with the blockchain. Could these be the case?

**Comment by pseudozach** [comment]
I think this happened because the final target node was canceling invoices and this is the error you get from immortan which was confusing to me. I'll close this and re-open if I find an actual problem.
